application: mazurwebapp
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/spi/.*
  script: main.application

- url: .*
  script: main.app

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: "2.5.2"
- name: endpoints
  version: 1.0
# Needed for endpoints/users_id_token.py.
- name: pycrypto
  version: "2.6"